### ISSUE TITLE
KeyVault references only work using SecretClient, "SSL connection could not be established" for SetCredential.

### ISSUE THREAD

**Issue by JosXa** [Azure/AppConfiguration-DotnetProvider#206]
I am running into an issue with the following code:

``` csharp
configurationBuilder.AddAzureAppConfiguration(appConfig =>
{
    appConfig
        .Connect(...)
        .ConfigureKeyVault(kv =>
        {
            TokenCredential credentials = new ChainedTokenCredential(
                new DefaultAzureCredential(),
                new ManagedIdentityCredential());

            // (A) This works:
            var secretClient = new SecretClient(new Uri("https://<mykeyvault>.vault.azure.net"), credentials);
            kv.Register(secretClient);

            // (B) This fails:
            // kv.SetCredential(credentials);
        });
        ...
    }
    ...
}
```

The interesting thing is that either version works on Azure, but our on-premise Jenkins server throws the following exception when trying to run the `kv.SetCredential()` version:

```
System.Exception : Retry failed after 3 tries. (The SSL connection could not be established, see inner exception.) (The SSL connection could not be established, see inner exception.) (The SSL connection could not be established, see inner exception.) (The SSL connection could not be established, see inner exception.) (The SSL connection could not be established, see inner exception.) (The SSL connection could not be established, see inner exception.)The SSL connection could not be established, see inner exception.   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message)
     at Azure.Core.Pipeline.RequestActivityPolicy.ProcessNextAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean isAsync)
     at Azure.Core.Pipeline.RequestActivityPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean isAsync)
     at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
     at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
     at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
     at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
     at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
     at Azure.Data.AppConfiguration.AuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
     at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)The SSL connection could not be established, see inner exception.   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message)
     at Azure.Core.Pipeline.RequestActivityPolicy.ProcessNextAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean isAsync)
     at Azure.Core.Pipeline.RequestActivityPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean isAsync)
     at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
     at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
     at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
     at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
     at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
     at Azure.Data.AppConfiguration.AuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
     at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)The SSL connection could not be established, see inner exception.   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message)
     at Azure.Core.Pipeline.RequestActivityPolicy.ProcessNextAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean isAsync)
     at Azure.Core.Pipeline.RequestActivityPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean isAsync)
     at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
     at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
     at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
     at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
     at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
     at Azure.Data.AppConfiguration.AuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
     at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
```

I was under the impression that both should be equivalent, as the Uri of the Key Vault is already encoded in the secret retrieved from App Configuration. Could this have something to do with restrictive firewall settings? I am not a fan of hard coding / duplicating the Uris to our Key Vaults in a bunch of secret clients when the program already has this information. 

(On another note, the exception could be better)

Any ideas how to debug this? Have I been banging my head against a bug or a feature for the past 6 hours? ^^

**Comment by abhilasharora** [comment]
@JosXa This seems to be related to requests to the App Configuration endpoint being blocked by the firewall. I would suggest checking the firewall settings and ensuring that `*.azconfig.io` is allow-listed.

**Comment by JosXa** [comment]
@abhilasharora awesome, that did the trick! Thanks a ton 🚀
