### ISSUE TITLE
Crashes with unclear error message when using package coverlet.collector

### ISSUE THREAD

**Issue by kristofferjalen** [Azure/AppConfiguration-DotnetProvider#374]
Using `Microsoft.Extensions.Configuration.AzureAppConfiguration`, version 5.2.0, it seems like test package `coverlet.collector` will stop the application from starting, giving this unclear stack trace:

```
at Program.<Main>(String[] args)
at Program.<Main>$(String[] args) in /home/vsts/work/1/s/foo/bar/Program.cs:line 11
at Microsoft.Extensions.Hosting.HostBuilder.Build()
at Microsoft.Extensions.Hosting.HostBuilder.InitializeAppConfiguration()
at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.Load()
at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.LoadAll(Boolean ignoreFailures, CancellationToken cancellationToken)
at Microsoft.Extensions.Configuration.AzureAppConfiguration.TracingUtils.CallWithRequestTracing(Boolean tracingEnabled, RequestType requestType, RequestTracingOptions requestTracingOptions, Func`1 clientCall)
at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.<>c__DisplayClass26_2.<<LoadAll>b__3>d.MoveNext()
at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.<>c__DisplayClass26_2.<<LoadAll>b__3>d.MoveNext()
at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()
at Azure.Data.AppConfiguration.ConfigurationClient.GetConfigurationSettingsPageAsync(SettingSelector selector, String pageLink, CancellationToken cancellationToken)
```

**Comment by amerjusupovic** [comment]
Hello @kristofferjalen , thank you for bringing up this issue. I'll be looking into this very soon.

**Comment by amerjusupovic** [comment]
I just have a few questions that could help me out:

1. Did you see this issue in 5.1.0 or a previous version as well?
2. Does the error occur on installation of the package or is there a code snippet you could share?
3. Did you recently change anything else like your App Configuration store or other parts of your application?

Thanks!
